### ISSUE TITLE
District Name Corrections

### ISSUE THREAD

**Issue by Tanmay53** [guneetnarula/indian-district-boundaries#4]
Khargone is the new name of West Nimar.
Chengalpattu has been carved out of Kancheepuram.

**Comment by guneetnarula** [comment]
Is this correct here? https://github.com/guneetnarula/indian-district-boundaries/tree/master/topojson/state-wise

**Comment by Tanmay53** [comment]
Yes, the names are correct in the state json files but I was looking in the geojson file which is now unstaged from the repository.
Thanks,
Regards
