### ISSUE TITLE
JSON File isn't getting imported into Power BI

### ISSUE THREAD

**Issue by mmb1793** [guneetnarula/indian-district-boundaries#6]
I downloaded the JSON File for one of the states and tried to get it imported into power BI for visualisation into a custom shape map, but when i load it, it doesn't work

**Comment by guneetnarula** [comment]
Does power BI support topojsons?

**Comment by mmb1793** [comment]
Yes, power BI supports TopoJSON files. I tried saving the file from github on the browser itself. Is that the right way to do it? or is there another way?

**Comment by mmb1793** [comment]
I figured it out. thank you so much. works great
